#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

export HAKO_RD_LITE_ENABLE="${HAKO_RD_LITE_ENABLE:-1}"
export HAKO_RD_LITE_NODE_ID="${HAKO_RD_LITE_NODE_ID:-1}"
export HAKO_RD_LITE_PEER_NODE_ID="${HAKO_RD_LITE_PEER_NODE_ID:-2}"
export HAKO_RD_LITE_INITIAL_OWNER="${HAKO_RD_LITE_INITIAL_OWNER:-1}"
export HAKO_RD_LITE_MAX_CONTEXT_BYTES="${HAKO_RD_LITE_MAX_CONTEXT_BYTES:-4096}"
export HAKO_RD_LITE_RELEASE_X="${HAKO_RD_LITE_RELEASE_X:-1.0}"
export HAKO_RD_LITE_HOME_X="${HAKO_RD_LITE_HOME_X:-1.0}"
export HAKO_RD_LITE_STANDBY_VIEWER="${HAKO_RD_LITE_STANDBY_VIEWER:-0}"
export HAKO_RD_LITE_STANDBY_PHYSICS="${HAKO_RD_LITE_STANDBY_PHYSICS:-1}"
export HAKO_RD_LITE_STANDBY_ALPHA="${HAKO_RD_LITE_STANDBY_ALPHA:-0.05}"
export HAKO_RD_LITE_STANDBY_TINT="${HAKO_RD_LITE_STANDBY_TINT:-0.20}"
export HAKO_RD_LITE_STANDBY_WELD="${HAKO_RD_LITE_STANDBY_WELD:-0}"
export HAKO_RD_LITE_STANDBY_ZERO_DYNAMICS="${HAKO_RD_LITE_STANDBY_ZERO_DYNAMICS:-1}"
export HAKO_LOCAL_STATE_ENABLE="${HAKO_LOCAL_STATE_ENABLE:-0}"

# Asset registration name must be unique.
export HAKO_ASSET_NAME="${HAKO_ASSET_NAME:-forklift-1}"
# Keep robot name as legacy "forklift" for current control/config compatibility.
export HAKO_FORKLIFT_ROBOT_NAME="${HAKO_FORKLIFT_ROBOT_NAME:-forklift}"
export HAKO_ASSET_CONFIG_PATH="${HAKO_ASSET_CONFIG_PATH:-config/forklift-unit.json}"
unset HAKO_CONFIG_PATH

export HAKO_FORKLIFT_STATE_FILE="${HAKO_FORKLIFT_STATE_FILE:-./tmp/forklift-1.state}"
export HAKO_RUN_LOG_FILE="${HAKO_RUN_LOG_FILE:-./logs/forklift-1-run.log}"
export HAKO_FORKLIFT_TRACE_FILE="${HAKO_FORKLIFT_TRACE_FILE:-./logs/forklift-1-trace.csv}"
export HAKO_FORKLIFT_RECOVERY_LOG_FILE="${HAKO_FORKLIFT_RECOVERY_LOG_FILE:-./logs/forklift-1-recovery.log}"
export HAKO_FORKLIFT_RESTORE_DEBUG_FILE="${HAKO_FORKLIFT_RESTORE_DEBUG_FILE:-./logs/forklift-1-restore-debug.csv}"

echo "[forklift-1] RD_LITE=${HAKO_RD_LITE_ENABLE} node=${HAKO_RD_LITE_NODE_ID} peer=${HAKO_RD_LITE_PEER_NODE_ID} owner=${HAKO_RD_LITE_INITIAL_OWNER}"
echo "[forklift-1] RELEASE_X=${HAKO_RD_LITE_RELEASE_X} HOME_X=${HAKO_RD_LITE_HOME_X}"
echo "[forklift-1] STANDBY_VIEWER=${HAKO_RD_LITE_STANDBY_VIEWER}"
echo "[forklift-1] STANDBY_PHYSICS=${HAKO_RD_LITE_STANDBY_PHYSICS}"
echo "[forklift-1] STANDBY_ALPHA=${HAKO_RD_LITE_STANDBY_ALPHA}"
echo "[forklift-1] STANDBY_TINT=${HAKO_RD_LITE_STANDBY_TINT}"
echo "[forklift-1] STANDBY_WELD=${HAKO_RD_LITE_STANDBY_WELD}"
echo "[forklift-1] STANDBY_ZERO_DYNAMICS=${HAKO_RD_LITE_STANDBY_ZERO_DYNAMICS}"
echo "[forklift-1] LOCAL_STATE_ENABLE=${HAKO_LOCAL_STATE_ENABLE}"
echo "[forklift-1] ASSET_NAME=${HAKO_ASSET_NAME} ROBOT_NAME=${HAKO_FORKLIFT_ROBOT_NAME}"
echo "[forklift-1] ASSET_CONFIG_PATH=${HAKO_ASSET_CONFIG_PATH}"
echo "[forklift-1] STATE_FILE=${HAKO_FORKLIFT_STATE_FILE}"
echo "[forklift-1] RECOVERY_LOG_FILE=${HAKO_FORKLIFT_RECOVERY_LOG_FILE}"
echo "[forklift-1] RESTORE_DEBUG_FILE=${HAKO_FORKLIFT_RESTORE_DEBUG_FILE}"

exec bash forklift-unit.bash "$@"
